### ISSUE TITLE
Question about capability: Capturing video from camera and Activity itself

### ISSUE THREAD

**Issue by darrinps** [spaceLenny/recordablesurfaceview#12]
I'm wondering if RecordableSurfaceView might be able to be used to send camera video to, and have it record that as well as whatever is on the screen (buttons, text, etc.). In other words, act just like a screen recorder where most of the input is from the camera with some additional overlay in the form of buttons/TextViews/etc. on top.

Is that possible with this? If so, is there any example of getting camera video to display using RecordableSurfaceView available?

**Comment by spaceLenny** [comment]
That's not a use case we've envisioned for this, but if you can get that to happen with a surface view, you could use RSV to record it. This library is mostly about saving the GL context to a video file.

**Comment by darrinps** [comment]
Understood. Was just hoping that it might work. Thanks for the fast reply.
