### ISSUE TITLE
EGL_BAD_SURFACE

### ISSUE THREAD

**Issue by kevin4dhd** [spaceLenny/recordablesurfaceview#13]
I am using Google OCR, so that the camera's source works in SurfaceView, merge the SurfaceView with recordablesurfaceview, align me to record this error, some solution please :(

This here is my LOG

![image](https://user-images.githubusercontent.com/22886367/60394246-f4b26b80-9ae6-11e9-891e-771404b97e55.png)

**Comment by spaceLenny** [comment]
From this logcat it seems as if the OCR library is trying to bind to the
persistent surface or the EGL window after it is already bound.

I haven't personally worked with the OCR library, what exactly does it do
in this case? Attempt to OCR your opengl output on screen?

**Comment by kevin4dhd** [comment]
Hello, thank you very much for answering, I will explain in detail what I am doing and what I want to do

I am using the GoogleOCR library to capture the code of the license plates, the GoogleOCR library allows text recognition with the camera.

I am using your library because I need to have evidence when making a recognition to the plate, or a video, I have spent more than a week trying everything to achieve it, but so far I have not been successful.

There is a part of the code where the camera starts to draw on a SurfaceView with the setPreviewDisplay method

![image](https://user-images.githubusercontent.com/22886367/60398914-306b2680-9b23-11e9-9b34-8344d51520b8.png)

As you can see it begins to draw the output of the camera on the surfaceview, I need to capture that

![65891864_205873083651538_3593891469217234944_n](https://user-images.githubusercontent.com/22886367/60399091-4e398b00-9b25-11e9-8ae7-a3f6becc3a05.jpg)

Download your sample project and if it works correctly, you can record everything without problem, for some reason you can not capture the surfaceview that is connected to the camera

If I had another idea of how to record what I am capturing would be very helpful, you can ask me any part of the code without problem

**Comment by spaceLenny** [comment]
Not sure if this means you got it working or not, was this an issue with RSV?
