### ISSUE TITLE
Recording without sound only works at second try

### ISSUE THREAD

**Issue by Noltibus** [spaceLenny/recordablesurfaceview#14]
I integrated your `RecordableSurfaceView` into my existing app to record ARCore scenes. However, I don't want to record audio, mainly because of the permission to the user, which could appear deterred. So I took your code, created my own `RecordableSurfaceView` and removed the lines regarding the audio source from the initialization of the `MediaRecorder`. But if I try to record, the first record is always corrupted. The longer I record, the bigger the file gets, but the increase is way to0 small compared to a non-corrupted file. After I stop and start the recording, the second and all further recordings will be without any errors.
This is the code of `MediaRecorder` initialization:

```
public void initRecorder(File saveToFile, int displayWidth, int displayHeight,
      int orientationHint, MediaRecorder.OnErrorListener errorListener,
      MediaRecorder.OnInfoListener infoListener) throws IOException {

    MediaRecorder mediaRecorder = new MediaRecorder();

    mediaRecorder.setOnInfoListener(infoListener);

    mediaRecorder.setOnErrorListener(errorListener);

    mediaRecorder.setVideoSource(MediaRecorder.VideoSource.SURFACE);
    mediaRecorder.setInputSurface(mSurface);
    //mediaRecorder.setAudioSource(AudioSource.DEFAULT);
    mediaRecorder.setOutputFormat(OutputFormat.DEFAULT);

//    mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
//    mediaRecorder.setAudioSamplingRate(44100);
//    mediaRecorder.setAudioEncodingBitRate(96000);

    mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.DEFAULT);

    mediaRecorder.setVideoEncodingBitRate(12000000);
    mediaRecorder.setVideoFrameRate(30);

    if (displayWidth > displayHeight) {
      mOutWidth = 1920;
      mOutHeight = 1080;
    }

    mediaRecorder.setVideoSize(mOutWidth, mOutHeight);

    mediaRecorder.setOrientationHint(orientationHint);

    mediaRecorder.setOutputFile(saveToFile.getPath());
    mediaRecorder.prepare();

    mMediaRecorder = mediaRecorder;

  }
```
So nothing fancy here. The initialization is called in `onResume()` of my MainActivity and `toggleRecording()` is implemented like in your example. If I include audio in my recording it works at first try. Any idea what I'm doing wrong?

**Comment by spaceLenny** [comment]
Any progress on this one? I was never able to reproduce this bug. If you have more info, I'd love to hear about it.
