### ISSUE TITLE
ARCore recording

### ISSUE THREAD

**Issue by IamMathankumar** [spaceLenny/recordablesurfaceview#19]
Can you please add a sample for ARCore recording with AR object

**Comment by spaceLenny** [comment]
I recommend taking a look at [JustALine](https://github.com/googlecreativelab/justaline-android) from Google Creative Lab. Its using RecordableSurfaceView to do its recording.

**Comment by IamMathankumar** [comment]
Ok, Thanks. But that code is not updated after 2018
 AR core codes changed a lot after that

**Comment by EAStudios** [comment]
You should Fix some Gradle errors, That's it!
