### ISSUE TITLE
Incorporating RecordableSurfaceView into SceneForm

### ISSUE THREAD

**Issue by oec08** [spaceLenny/recordablesurfaceview#4]
Would you happen to know how to incorporate this project into the [Scene Form SDK](https://github.com/google-ar/sceneform-android-sdk) ? That project has an underlying SurfaceView attached to the scene.

**Comment by spaceLenny** [comment]
It seems to me that using a combination of subclassing RecordableSurfaceView, and getting the underlying persistent surface with `this.getHolder().getSurface()` and  [startMirroringToSurface](https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/SceneView#startMirroringToSurface(android.view.Surface,%20int,%20int,%20int,%20int)) in SceneForm may be what you're looking for but I can't speak from personal experience.
